// A list of all Tags that cards can have

export const cardTags = [
    "Alternate Summoning",
    "Alternate Win Condition",
    "Any Tribal",
    "Aquatic Tribal",
    "Aquatic Counter",
    "Beast Removal",
    "Beast Tutor",
    "Best Character",
    "Board Interaction",
    "Board Wipe",
    "Buff",
    "Byeah Tribal",
    "Card Attachment",
    "Card Draw",
    "Card Search",
    "Coin Flip",
    "Combo",
    "Crabcha Tribal",
    "Deathtouch",
    "Debuff",
    "Defender",
    "Dice Rolling",
    "Discard",
    "Discard Beast Tribal",
    "Discard Interaction",
    "Draw",
    "Epic Tribal",
    "Foodie Tribal",
    "Free Summoning",
    "Gambling",
    "Ghostly Tribal",
    "Grotto Removal",
    "Grotto Tribal",
    "Gruffling Tribal",
    "Hand Disruption",
    "Hand Size",
    "Haste",
    "Hexproof",
    "Jup Tribal",
    "Mill",
    "OP",
    "Phase Interaction",
    "Protection",
    "Rat Tribal",
    "Reviving",
    "Rock-Paper-Scissors",
    "Sacrifice",
    "Score Interaction",
    "Scoring",
    "Scry",
    "Sideline",
    "Singleton",
    "Sleepy",
    "Summoning Pool Interaction",
    "Tapping",
    "Thoughtseize",
    "Tie-Break",
    "Tribal",
    "Unique Beast tribal",
    "Vigilance",
    "Voltron",
    "Wish Counter",
    "Wish Tribal",
    "Wizard Tribal",
    "Worst Character",
    "Zoo"
]